version: '3'
services:
  monolito:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - ./src:/usr/src/app/src
    command: npm run start:dev
    networks:
      - app-network
    depends_on:
      - db
  db:
    image: mysql:latest
    container_name: GestionTareasDB
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: GestionTareasDB
    ports:
      - '3306:3306'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge